# Generated by Django 2.2.7 on 2020-01-26 04:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_sueltas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('medida', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('paquetes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidadesSueltas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidades', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('existencias', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='salida',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='empaquetado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='paquetes',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sueltas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Producto'),
        ),
    ]
